(require 'auto-complete)
(require 'auto-complete-config)
(global-auto-complete-mode t)
(setq ac-auto-start nil)
(ac-set-trigger-key "TAB")
(add-to-list 'ac-dictionary-directories "/home/soh.i/.emacs.d/elpa/auto-complete-20130724.1750/dict")
(ac-config-default)
(setq ac-delay 0.0001)
(setq ac-auto-show-menu 0.0001)

